name: Solution-Checker
on:  
  workflow_dispatch:

jobs:
  solutioncheck:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v
      
      - name: Check-solution
        uses: microsoft/powerplatform-actions/check-solution@1
        with:
          environment-url: ""
          app-id: ""
          client-secret:""
          tenant-id: ""
          path: ""
        
        

      
